# Similarity-Only Benchmark Configuration
# @package benchmark

# List of benchmarks to run (only similarity)
benchmarks:
  - _target_: benchmark.reproducibility_benchmark.ReproducibilityBenchmark
    name: "similarity"
